### ISSUE TITLE
Best way to add project specific validation

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda-verify#10]
What is the best way to add project specific validation?
Eg conda-forge may want to check that all the example recipe comments have been removed.

**Comment by mandeep** [comment]
@CJ-Wright Currently, if you want to add project specific validation you would have to write your own check. Hopefully the next release or a future release of conda-verify will be a bit more extensible in that regard.

**Comment by CJ-Wright** [comment]
So that check would not go into conda-verify?

**Comment by mandeep** [comment]
Sorry, I may be confused. Were you asking of a general way to add project specific validation, or did you want to add a specific check to check for comments in recipes?

**Comment by CJ-Wright** [comment]
Conda-forge has specific comments in their example recipe. This recipe is usually copied and edited. It would be nice to have a way to make certain that these are deleted before accepting the recipe. This is where I thought conda-verify could come in to check if the conda-forge example comments are removed.

I think this is a conda-forge specific problem.

**Comment by mandeep** [comment]
I see now. Thanks for bringing this up. I'll add this check in the next release based on the recipe found here: https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml

**Comment by CJ-Wright** [comment]
Here are some relevant conda-forge issues:
https://github.com/conda-forge/conda-smithy/issues/512
https://github.com/conda-forge/conda-smithy/pull/475#issuecomment-285912346

**Comment by mandeep** [comment]
Thanks!

**Comment by mandeep** [comment]
Check added in #11

**Comment by CJ-Wright** [comment]
I'm a little confused, are there docs now that state how to add project specific validation? Can you give me a link?

**Comment by mandeep** [comment]
The added check was for the conda-forge comments in meta.yaml. If there are any other conda-forge checks that you'd like to see please let me know or submit a PR.

**Comment by CJ-Wright** [comment]
All the conda-forge checks are here: https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/lint_recipe.py

Some are very specific to conda-forge/github. Would it be possible to add them?
