### ISSUE TITLE
summary length of 80 is not documented

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-verify#26]
conda-verify complains if the summary is longer than 80 characters, but this [is not documented](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html).  Furthermore, this number seems rather arbitrary to me and leads to problems if you import projects (and their summary) from PyPI into conda.

**Comment by mandeep** [comment]
By leads to problems do you mean you're running into undefined behavior because of ``C2117``?

**Comment by sscherfke** [comment]
*leads to problems* means *many Python projects have descriptions longer than 80chars and I don’t want to trim them when I convert the packages to Conda packages*.

**Comment by mandeep** [comment]
I'll leave this up for discussion whether or not we should remove ``C2117``. @sscherfke in the meantime you can use the ignore flag to ignore this check.

**Comment by sscherfke** [comment]
Anyways, this limit should be documented in the meta-yaml docs. ;)
