### ISSUE TITLE
C2110 Found invalid field "git_rev" in section "source"

### ISSUE THREAD

**Issue by parente** [conda/conda-verify#39]
Not sure if this is a bug in verification or not. The metadata doc lists `git_rev` as a valid key in the `source` section but conda-verify 3 flags it as invalid.

https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html

**Comment by mandeep** [comment]
Can you show me the error you're seeing?

**Comment by parente** [comment]
Sure. It's basically the title of this issue. Here it is with internal build details obscured:

```
04:49:06 /var/jenkins/workspace/XXXXX/src/specs/somepkg-python: C2110 Found invalid field "git_rev" in section "source"
```

The spec source section looks like:

```
{% set version = "2.2.8" %}
{% set name = "somepackage" %}

# ellided package section

source:
  git_url: {{ ssh_host }}/xx/somerepo.git
  git_rev: {{ version }}
```

We hit this with conda-verify-3.0.1-py36_0. Reverting to conda-verify-2.0.0 works around the problem.

**Comment by mandeep** [comment]
Thanks! The git_rev field is missing from the valid fields in constants.py. I'll submit a PR to fix this.
