### ISSUE TITLE
TypeError in check_windows_arch (menuinst package CI)

### ISSUE THREAD

**Issue by carlodri** [conda/conda-verify#43]
In PR conda-forge/menuinst-feedstock#2, AppVeyor CI fails with the following error:

```bash
INFO:conda.gateways.disk.delete:rm_rf failed for c:\users\appveyor\appdata\local\temp\1\tmpl4pwk8
Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1524, in build_tree
    config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1159, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 939, in bundle_conda
    path_to_package=tmp_path)
  File "C:\Miniconda-x64\lib\site-packages\conda_verify\verify.py", line 30, in verify_package
    getattr(package_check, method)() is not None]
  File "C:\Miniconda-x64\lib\site-packages\conda_verify\checks.py", line 309, in check_windows_arch
    file_object_type = get_object_type(file_header)
  File "C:\Miniconda-x64\lib\site-packages\conda_verify\utilities.py", line 117, in get_object_type
    return "DLL " + DLL_TYPES.get(i)
TypeError: cannot concatenate 'str' and 'NoneType' objects
Command exited with code 1
```

It looks like there could be something wrong in the parsing of `.exe` or `.dll` headers in the [`get_object_type`](https://github.com/conda/conda-verify/blob/master/conda_verify/utilities.py#L109) function.

Relevant files of the package are [here](https://anaconda.org/conda-forge/menuinst/files).

See also https://github.com/regro/cf-scripts/issues/46.

**Comment by mandeep** [comment]
Thanks for reporting this. Could you let me know which version of Python your Miniconda installation is using and your conda-verify version.

**Comment by carlodri** [comment]
The CI fails for py27, version of conda-verify should be the latest. You can check logs here: https://ci.appveyor.com/project/conda-forge/menuinst-feedstock/build/1.0.3

**Comment by carlodri** [comment]
I'm not sure about the conda-verify version. @jakirkham can you help?

**Comment by mandeep** [comment]
@carlodri you can check the version by typing ``conda-verify --version`` into the terminal.

**Comment by jakirkham** [comment]
Looking at the log it appears to be 3.0.1.

**Comment by mandeep** [comment]
@carlodri Thanks for reporting this. It looks like a Python 2 related bug has surfaced. I'll see if I can submit a PR for this soon.

**Comment by carlodri** [comment]
> Looking at the log it appears to be 3.0.1.

Thanks @jakirkham

**Comment by mandeep** [comment]
@carlodri @jakirkham I am unable to replicate this with the menuinst packages listed on anaconda.org. I tried building the package from the recipe with conda-build, but ran into other issues. Are either of you able to replicate this issue with the anaconda.org Py27 packages and Python2 on Windows?

**Comment by carlodri** [comment]
it happened again here https://github.com/conda-forge/memory_profiler-feedstock/pull/12 (relevant CI [here](https://ci.appveyor.com/project/conda-forge/memory-profiler-feedstock/build/1.0.19/job/bp6dp0lyi7tqn0l7))

**Comment by carlodri** [comment]
@mandeep I'm not sure about how to test on my machine: should I simply install `conda-verify` and run it on the package created with `conda-build`?

**Comment by mandeep** [comment]
@carlodri That should work, the only difference may be that you may have to install conda-verify from the git repo rather than conda as I'm not sure if the new version is available on any of the conda channels. Let me know if you need help with the installation. I appreciate your assistance with this!
