### ISSUE TITLE
C1115 is based on definitions with incoherent case

### ISSUE THREAD

**Issue by debrando** [conda/conda-verify#48]
On "constants.py" when "conda_build.license_family.allowed_license_families" is not avaible the licenses are (somewhat) CamelCase, but "allowed_license_families" defines all as uppercase. On the other hands, an uppercase "PROPRIETARY" doesn't look so common, so maybe it could be better a case-insensitive control.

**Comment by rolweber** [comment]
I also just fell for this one. The fallbacks are mixed case, but the list actually used is all-uppercase:
https://github.com/conda/conda-build/blob/master/conda_build/license_family.py#L8-L23
