### ISSUE TITLE
C1115 Found invalid license "Proprietary" in info/index.json

### ISSUE THREAD

**Issue by dazza-codes** [conda/conda-verify#64]
According to notes in #55, the 'Proprietary' option is among the allowed license families.  What makes this "invalid"?  Is this just a matter of using case-insensitive checks?

## code links
- https://github.com/conda/conda-verify/blob/master/conda_verify/checks.py#L915
  - uses literal, case-sensitive checks (not regex patterns)
- https://github.com/conda/conda-verify/blob/master/conda_verify/checks.py#L25
- https://github.com/conda/conda-verify/blob/master/conda_verify/constants.py#L8
  - uses all-caps strings

**Comment by mandeep** [comment]
Yes, this seems to be a case of case sensitivity. We could make this check case insensitive, however https://github.com/conda/conda-build/issues/2015 should be the target.
