### ISSUE TITLE
CondaPackageCheck fails with AttributeError when building `noarch` package.

### ISSUE THREAD

**Issue by nanthony21** [conda/conda-verify#65]
A package that builds fine for Windows is failing when I try to build as a "noarch" package.

The traceback I get is here: https://www.heypasteit.com/clip/0ITXRY

The line where this error is occurring is here: https://github.com/conda/conda-verify/blob/d0d6be89ca5d37bb0f83469345cf987b55d7171e/conda_verify/checks.py#L92

Looking through the code i see that other parts of the code reference `self.info['subdir']` rather than `self.info.subdir`. This fixed the attribute error but the assertion still fails: `assert self.info["subdir"] == 'noarch' AssertionError`

The only step I took to try building as "noarch" was add `noarch_python: True` under the `build:` section of my conda recipe `meta.yaml`. Is there something I'm missing?

**Comment by nanthony21** [comment]
Just saw that Pull Request #63  references this exact issue. Following its lead and removing the problematic line appears to have solved the issue for me.

**Comment by mandeep** [comment]
Thanks for the reminder. #63 was merged and should be included in a future release.
