### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-verify#7]
Am a little unclear on the requirements of this package. Does it depend on `conda`, some sort of `yaml` parser, etc.? Maybe including a development recipe in this repo would help make this information more accessible.

**Comment by mandeep** [comment]
Hi @jakirkham!

conda-verify does not depend on conda and there are currently no dependencies that are installed alongside the conda-verify package. I'm currently working on updating conda-verify and will include the development recipe on the next release.

**Comment by jakirkham** [comment]
Thanks for the update. A development recipe would be great. Is this something you are planning to use in CI as well?

**Comment by mandeep** [comment]
I believe so.

**Comment by mandeep** [comment]
I'm marking this issue as resolved. If you still have questions, feel free to reopen.
