### ISSUE TITLE
Doesn't support `.conda`

### ISSUE THREAD

**Issue by dholth** [conda/conda-verify#88]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I changed `conda-build` to output `.conda` and `conda-verify` failed

```
conda-build:
    pkg_format: 2
```

**Comment by dholth** [comment]
Actually the error message from conda-build is near `conda-verify` but caused by something else.

**Comment by mfansler** [comment]
What did you see? What was the resolution?

**Comment by dholth** [comment]
I don't remember, it was way back in September.
